version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      eslint:
        patterns: ["eslint", "eslint-*", "@typescript-eslint/*"]
      jest:
        patterns: ["jest", "@jest/*"]
      typescript:
        patterns: ["typescript", "@types/*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
